# RockTimer - Pi 4 (Central Server + Hog Close sensor)

device_id: "hog_close"

gpio:
  sensor_pin: 17      # Timing sensor (laser)
  arm_pin: 27         # Arm sensor (IR) - hold hand in front to arm
  debounce_ms: 50

server:
  host: "0.0.0.0"
  http_port: 8080
  udp_port: 5000
  alsa_device: "hw:0,0"
  auto_arm_on_start: true
